"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, CheckCircle2, ChevronDown, FileText, GraduationCap, Loader2, Lock, LogOut, Play, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";

interface Chapter { id: string; week_number: number; title: string; unlocked: boolean; body: string | null; file_url: string | null; zoom_link: string | null; zoom_time: string | null; exam_result: { score: number; total: number; passed: boolean } | null; }
interface Question { id: string; question: string; options: string[]; }

export default function AcademyCoursePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [student, setStudent] = useState<{ name: string; current_week: number; track: { name: string; total_weeks: number } } | null>(null);
  const [chapters, setChapters] = useState<Chapter[]>([]);
  const [openWeek, setOpenWeek] = useState<string | null>(null);
  const [examQuestions, setExamQuestions] = useState<Question[]>([]);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [examResult, setExamResult] = useState<{ score: number; total: number; passed: boolean } | null>(null);
  const [loadingExam, setLoadingExam] = useState(false);
  const [submittingExam, setSubmittingExam] = useState(false);

  const load = useCallback(async () => { const res = await fetch("/api/academy/me"); if (res.status === 401) { router.push("/academy/login"); return; } const data = await res.json(); setStudent(data.student); setChapters(data.chapters || []); setLoading(false); }, [router]);
  useEffect(() => { load(); }, [load]);
  async function openChapter(chapter: Chapter) { if (openWeek === chapter.id) { setOpenWeek(null); return; } setOpenWeek(chapter.id); setExamResult(chapter.exam_result); setAnswers({}); setExamQuestions([]); if (!chapter.exam_result) { setLoadingExam(true); try { const res = await fetch(`/api/academy/exam/${chapter.id}`); const data = await res.json(); setExamQuestions(data.questions || []); } finally { setLoadingExam(false); } } }
  async function submitExam(chapterId: string) { setSubmittingExam(true); try { const res = await fetch("/api/academy/exam/submit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chapter_id: chapterId, answers: examQuestions.map((_, index) => answers[index] ?? -1) }) }); const data = await res.json(); if (res.ok) setExamResult(data.result); } finally { setSubmittingExam(false); } }
  async function handleLogout() { await fetch("/api/academy/login", { method: "DELETE" }); router.push("/academy/login"); }

  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#140a27]"><Loader2 className="h-7 w-7 animate-spin text-violet-200" /></div>;
  if (!student) return null;
  const progress = Math.round((student.current_week / student.track.total_weeks) * 100);
  const current = chapters.find((chapter) => chapter.week_number === student.current_week && chapter.unlocked);

  return <div className="min-h-screen bg-[#140a27] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-400 text-slate-950"><GraduationCap className="h-5 w-5" /></span><div><p className="text-sm font-bold">Guri Dagan Academy</p><p className="text-xs text-violet-100/60">{student.track.name}</p></div></div><Button variant="ghost" size="sm" onClick={handleLogout} className="gap-2 text-violet-100/65 hover:bg-white/10 hover:text-white"><span className="hidden sm:inline">Log out</span><LogOut className="h-4 w-4" /></Button></div></header><main className="mx-auto max-w-5xl px-5 py-8 sm:px-8 sm:py-12"><section className="rounded-[2rem] border border-violet-300/15 bg-gradient-to-br from-violet-400/20 to-white/[0.05] p-6 shadow-2xl shadow-black/20 sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-violet-200">Your learning journey</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Welcome back, {student.name.split(" ")[0]}.</h1><p className="mt-3 text-violet-100/70">You&apos;re in week {student.current_week} of {student.track.total_weeks}. Small steps add up.</p></div><span className="w-fit rounded-full bg-emerald-300/15 px-3 py-1.5 text-sm font-semibold text-emerald-200">{progress}% complete</span></div><div className="mt-8"><div className="mb-2 flex justify-between text-sm text-violet-100/75"><span>Course progress</span><span>Week {student.current_week} of {student.track.total_weeks}</span></div><Progress value={progress} className="h-3 bg-white/10" /></div></section>
    {current && <section className="mt-6 rounded-3xl border border-amber-200/20 bg-amber-200/[0.08] p-5 sm:flex sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-amber-100/80">This week</p><h2 className="mt-1 text-lg font-bold">Week {current.week_number}: {current.title}</h2><p className="mt-1 text-sm text-violet-100/65">Your current chapter is ready when you are.</p></div><button onClick={() => openChapter(current)} className="mt-4 inline-flex items-center gap-2 font-semibold text-amber-100 hover:text-white sm:mt-0">{openWeek === current.id ? "Close lesson" : "Open lesson"}<ChevronDown className={`h-4 w-4 transition ${openWeek === current.id ? "rotate-180" : ""}`} /></button></section>}
    <section className="mt-10"><div className="mb-5"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-violet-200">Course plan</p><h2 className="mt-1 text-2xl font-bold">Your weekly lessons</h2></div><div className="space-y-3">{chapters.map((chapter) => { const isCurrent = chapter.week_number === student.current_week; const isOpen = openWeek === chapter.id; const complete = Boolean(chapter.exam_result?.passed); return <article key={chapter.id} className={`overflow-hidden rounded-2xl border transition ${chapter.unlocked ? isCurrent ? "border-amber-200/35 bg-amber-200/[0.07]" : "border-white/10 bg-white/[0.05]" : "border-white/5 bg-white/[0.025] opacity-60"}`}><button onClick={() => chapter.unlocked && openChapter(chapter)} disabled={!chapter.unlocked} className="flex w-full items-center gap-4 p-4 text-left sm:p-5"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${complete ? "bg-emerald-300/15 text-emerald-200" : isCurrent ? "bg-amber-200/15 text-amber-100" : chapter.unlocked ? "bg-violet-400/15 text-violet-200" : "bg-white/5 text-violet-100/45"}`}>{complete ? <CheckCircle2 className="h-5 w-5" /> : chapter.unlocked ? <Play className="h-4 w-4 fill-current" /> : <Lock className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold uppercase tracking-[0.12em] text-violet-100/50">Week {chapter.week_number}</span><span className="mt-0.5 block font-semibold text-white">{chapter.title}</span></span>{complete ? <span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-xs font-semibold text-emerald-200">Complete</span> : isCurrent ? <span className="rounded-full bg-amber-200/10 px-2.5 py-1 text-xs font-semibold text-amber-100">This week</span> : chapter.unlocked ? <ChevronDown className={`h-5 w-5 text-violet-100/60 transition ${isOpen ? "rotate-180" : ""}`} /> : <span className="text-xs text-violet-100/45">Locked</span>}</button>{isOpen && <LessonDetail chapter={chapter} result={examResult} questions={examQuestions} answers={answers} loading={loadingExam} submitting={submittingExam} onAnswer={(question, answer) => setAnswers((currentAnswers) => ({ ...currentAnswers, [question]: answer }))} onSubmit={() => submitExam(chapter.id)} />}</article>; })}</div></section></main></div>;
}

function LessonDetail({ chapter, result, questions, answers, loading, submitting, onAnswer, onSubmit }: { chapter: Chapter; result: { score: number; total: number; passed: boolean } | null; questions: Question[]; answers: Record<number, number>; loading: boolean; submitting: boolean; onAnswer: (question: number, answer: number) => void; onSubmit: () => void; }) { return <div className="border-t border-white/10 px-5 pb-6 pt-5 sm:px-6"><div className="grid gap-3 sm:grid-cols-2">{chapter.file_url && <a href={chapter.file_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl bg-white/[0.06] p-4 text-sm font-semibold hover:bg-white/[0.1]"><FileText className="h-5 w-5 text-violet-200" /> Open chapter material</a>}{chapter.zoom_link && <a href={chapter.zoom_link} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl bg-white/[0.06] p-4 text-sm font-semibold hover:bg-white/[0.1]"><Video className="h-5 w-5 text-violet-200" /> {chapter.zoom_time ? `Join live session - ${chapter.zoom_time}` : "Join live session"}</a>}</div>{chapter.body && <div className="mt-5 rounded-xl bg-black/10 p-4 text-sm leading-6 text-violet-100/75 whitespace-pre-wrap">{chapter.body}</div>}<div className="mt-6 border-t border-white/10 pt-5"><div className="mb-4 flex items-center gap-2"><BookOpen className="h-4 w-4 text-violet-200" /><h3 className="font-bold">End-of-week check-in</h3></div>{result ? <div className={`rounded-xl border p-4 text-sm ${result.passed ? "border-emerald-300/20 bg-emerald-300/10 text-emerald-100" : "border-amber-200/20 bg-amber-200/10 text-amber-100"}`}><strong>{result.passed ? "Completed" : "Keep practising"}</strong><span className="ml-2">Score: {result.score}/{result.total}</span></div> : loading ? <Loader2 className="h-5 w-5 animate-spin text-violet-200" /> : questions.length ? <div className="space-y-5">{questions.map((question, index) => <fieldset key={question.id}><legend className="text-sm font-semibold">{index + 1}. {question.question}</legend><div className="mt-3 grid gap-2">{question.options.map((option, optionIndex) => <label key={optionIndex} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm transition ${answers[index] === optionIndex ? "border-violet-300 bg-violet-400/15 text-white" : "border-white/10 text-violet-100/75 hover:bg-white/[0.05]"}`}><input type="radio" name={`question-${index}`} checked={answers[index] === optionIndex} onChange={() => onAnswer(index, optionIndex)} className="accent-violet-400" />{option}</label>)}</div></fieldset>)}<Button onClick={onSubmit} disabled={submitting} className="bg-violet-400 font-bold text-slate-950 hover:bg-violet-300">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : "Submit check-in"}</Button></div> : <p className="text-sm text-violet-100/55">There is no check-in for this chapter yet.</p>}</div></div>; }
